# Generated by Django 3.1.6 on 2021-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Первый слайдер'),
        ),
    ]
