# Generated by Django 3.1.6 on 2021-02-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_partners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
