# Generated by Django 3.1.6 on 2021-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Аукционы')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Аукционы',
            },
        ),
    ]
