# Generated by Django 3.1.6 on 2021-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Аукционы'),
        ),
    ]
