# Generated by Django 3.1.6 on 2021-02-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='e-mail')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(blank=True, max_length=150, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=150, null=True, verbose_name='Пароль')),
                ('fio', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Информация про участника')),
            ],
        ),
    ]
