# Generated by Django 3.1.6 on 2021-02-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='edrpo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ЄДРПОУ'),
        ),
    ]
