# Generated by Django 3.1.6 on 2021-02-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_edrpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
