# Generated by Django 3.1.6 on 2021-02-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='e-mail')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('edrpo', models.CharField(max_length=150, verbose_name='ЄДРПОУ')),
                ('message', models.TextField(verbose_name='Информация про участника')),
            ],
        ),
    ]
