# Generated by Django 3.1.6 on 2021-02-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
