# Generated by Django 3.1.6 on 2021-02-05 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='e-mail')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('edrpo', models.CharField(max_length=150, verbose_name='ЄДРПОУ')),
                ('message', models.TextField(verbose_name='Информация про участника')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
