# Generated by Django 3.1.6 on 2021-02-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contact_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='buyer',
        ),
    ]
