# Generated by Django 3.1.6 on 2021-02-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csvbase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_lot', models.CharField(blank=True, max_length=150, null=True, verbose_name='№ лоту')),
                ('p_lot', models.CharField(blank=True, max_length=150, null=True, verbose_name='П/лот')),
                ('seller', models.CharField(blank=True, max_length=150, null=True, verbose_name='Продавець')),
                ('product_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Продукція')),
                ('product_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Порода')),
                ('product_kind', models.CharField(blank=True, max_length=150, null=True, verbose_name='Гатунок')),
                ('product_diameter', models.CharField(blank=True, max_length=150, null=True, verbose_name='Діаметр (см)')),
                ('product_length', models.CharField(blank=True, max_length=150, null=True, verbose_name='Довжина (м)')),
                ('storehouse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Склад')),
                ('product_size', models.CharField(blank=True, max_length=150, null=True, verbose_name="Об'єм (м3)")),
                ('start_product_price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Початкова ціна (куб.м.)')),
                ('start_lot_price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Початкова ціна (лот)')),
                ('end_product_price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Продажна ціна (куб.м.)')),
                ('end_lot_price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Продажна ціна (лот)')),
                ('buyer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Найменування покупця')),
                ('EDRPOU', models.CharField(blank=True, max_length=150, null=True, verbose_name='код ЄДРПОУ')),
                ('PDV_certificate', models.CharField(blank=True, max_length=150, null=True, verbose_name='№ свідоцтва плати ПДВ')),
                ('IPN', models.CharField(blank=True, max_length=150, null=True, verbose_name='Інд. Податковий номер (ІПН)')),
                ('buyer_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юр.адреса')),
                ('contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефони')),
            ],
            options={
                'verbose_name': 'CSV',
                'verbose_name_plural': 'Выгрузка CSV',
            },
        ),
    ]
