# Generated by Django 3.1.6 on 2021-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scv', models.FileField(blank=True, null=True, upload_to='CSV/', verbose_name='Добавить SCV')),
            ],
            options={
                'verbose_name': 'Загрузка на сервер CSV',
                'verbose_name_plural': 'CSV',
            },
        ),
    ]
