# Generated by Django 3.1.6 on 2021-02-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0006_addcsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addcsv',
        ),
    ]
