# Generated by Django 3.1.6 on 2021-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0009_auto_20210208_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcsv',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
