# Generated by Django 3.1.6 on 2021-02-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0011_remove_addcsv_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addcsv',
        ),
    ]
