# Generated by Django 3.1.6 on 2021-02-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0015_csvbase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvbase',
            name='date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дата'),
        ),
    ]
