# Generated by Django 3.1.6 on 2021-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0016_auto_20210214_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvbase',
            name='commission',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='комісійний збір'),
        ),
        migrations.AddField(
            model_name='csvbase',
            name='quarter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='квартал'),
        ),
    ]
