# Generated by Django 3.1.6 on 2021-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvbase', '0018_remove_csvbase_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва підприємства')),
                ('director', models.CharField(blank=True, max_length=150, null=True, verbose_name='в особі керівника')),
                ('fio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Керівник ПІП')),
                ('statut', models.CharField(blank=True, max_length=150, null=True, verbose_name='на підставі')),
                ('cod', models.CharField(blank=True, max_length=150, null=True, verbose_name='КОД')),
                ('number_pdv', models.CharField(blank=True, max_length=150, null=True, verbose_name='№свідоцтва плати ПДВ')),
                ('individual_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Інд.подат. номер')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юридична адреса')),
                ('mailing_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Поштова адреса')),
                ('score', models.CharField(blank=True, max_length=150, null=True, verbose_name='Рахунок')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='ТЕЛЕФОНИ')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-Mail')),
                ('region', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва підприємства')),
            ],
            options={
                'verbose_name': 'Сельхозы',
                'verbose_name_plural': 'Список сельхозов',
            },
        ),
    ]
